sudo: required
language: node_js
node_js: 
- "4.1"
install:
- "curl https://install.meteor.com | /bin/sh"
- "npm install"
script:
- "meteor test --once --driver-package practicalmeteor:mocha-console-runner"
