import { N } from './n.js';

export const L = {
  archives: N.lensProp('archives'),
  cardCode: N.lensProp('card_code'),
  cards: N.lensProp('cards'),
  clicks: N.lensProp('clicks'),
  credits: N.lensProp('credits'),
  deckCards: N.lensProp('deck_cards'),
  discard: N.lensProp('discard'),
  hand: N.lensProp('hand'),
  hardware: N.lensProp('hardware'),
  hq: N.lensProp('hq'),
  ices: N.lensProp('ices'),
  maxClicks: N.lensProp('max_clicks'),
  maxHandSide: N.lensProp('max_hand_size'),
  mulligan: N.lensProp('mulligan'),
  programs: N.lensProp('programs'),
  ready: N.lensProp('ready'),
  remoteServers: N.lensProp('remote_servers'),
  resources: N.lensProp('resources'),
  rezzed: N.lensProp('rezzed'),
  rnd: N.lensProp('rnd'),
  turn: N.lensProp('turn'),
  turnOwner: N.lensProp('turn_owner'),
  upgrades: N.lensProp('upgrades'),
  wait: N.lensProp('wait'),
};
